import type { MapConfig } from "../types";

export const HOSPITAL_MAP: MapConfig = {
  id: "hospital",
  name: "St. Mercy Hospital",
  description: "An abandoned medical facility shrouded in darkness. Restore power, survive the horrors within, and face the Hive Mind in the operating theater.",
  worldWidth: 2000,
  worldHeight: 1600,
  arenaWidth: 800,
  arenaHeight: 600,
  playerStart: { x: 1000, y: 1400 },
  backgroundColor: "#0a0a0f",
  gridColor: "rgba(80,80,100,0.15)",
  hasDarkness: true,
  hasFlashlight: true,
  hasGenerator: true,
  generatorPos: { x: 1000, y: 1000 },
  stations: [
    { wx: "smg", x: 300, y: 900, label: "Emergency" },
    { wx: "shotgun", x: 1700, y: 300, label: "Pharmacy" },
    { wx: "rifle", x: 1700, y: 900, label: "Radiology" },
    { wx: "plasma", x: 1700, y: 1300, label: "Lab Storage" },
  ],
  worldObjects: [
    { pos: { x: 300, y: 1300 }, color: "#00ffff", radius: 10, questId: "sq_labvault", stepId: "k1" },
    { pos: { x: 1700, y: 1300 }, color: "#00ffff", radius: 10, questId: "sq_labvault", stepId: "k2" },
    { pos: { x: 300, y: 300 }, color: "#00ffff", radius: 10, questId: "sq_labvault", stepId: "k3" },
  ],
  mainQuest: [
    {
      id: "m1",
      text: "Find the Generator in the Basement",
      type: "reach",
      location: { x: 1000, y: 1000 },
      done: false,
    },
    {
      id: "m2",
      text: "Turn on the Power",
      type: "interact",
      done: false,
    },
    {
      id: "m3",
      text: "Purge the horde: kill 12 zombies",
      type: "kill",
      target: 12,
      progress: 0,
      done: false,
    },
    {
      id: "m4",
      text: "Reach the Operating Theater",
      type: "reach",
      location: { x: 1000, y: 400 },
      done: false,
    },
    {
      id: "m5",
      text: "Enter the Hive Mind's Lair",
      type: "reach",
      location: { x: 1000, y: 400 },
      done: false,
    },
  ],
  sideQuests: [
    {
      id: "sq_labvault",
      title: "The Lab Vault",
      accepted: true,
      done: false,
      reward: "PROTOTYPE_WEAPONS",
      steps: [
        {
          id: "k1",
          text: "Find Lab Key — Patient Ward",
          type: "reach",
          location: { x: 300, y: 1300 },
          done: false,
        },
        {
          id: "k2",
          text: "Find Lab Key — Lab Storage",
          type: "reach",
          location: { x: 1700, y: 1300 },
          done: false,
        },
        {
          id: "k3",
          text: "Find Lab Key — Research Lab",
          type: "reach",
          location: { x: 300, y: 300 },
          done: false,
        },
      ],
    },
    {
      id: "sq_supplies",
      title: "Medical Supplies: Recover 4 Crates",
      accepted: true,
      done: false,
      reward: 400,
      steps: [
        {
          id: "s1",
          text: "Recover supplies — Emergency Wing",
          type: "reach",
          location: { x: 300, y: 900 },
          done: false,
        },
        {
          id: "s2",
          text: "Recover supplies — Pharmacy",
          type: "reach",
          location: { x: 1700, y: 300 },
          done: false,
        },
        {
          id: "s3",
          text: "Recover supplies — Radiology",
          type: "reach",
          location: { x: 1700, y: 900 },
          done: false,
        },
        {
          id: "s4",
          text: "Recover supplies — Patient Ward",
          type: "reach",
          location: { x: 300, y: 1300 },
          done: false,
        },
      ],
    },
  ],
  gatePos: { x: 1000, y: 400 },
  bossType: "hivemind",
  bossHp: 1800,
  bossRadius: 50,
  easterEggType: "labvault",
};
