import type { MapConfig } from "../types";

export const OUTPOST_MAP: MapConfig = {
  id: "outpost",
  name: "The Outpost",
  description: "A fortified survivor settlement. Hold the line against the undead horde and enter the underworld arena to face The Harvester.",
  worldWidth: 2400,
  worldHeight: 1800,
  arenaWidth: 1200,
  arenaHeight: 900,
  playerStart: { x: 900, y: 900 },
  backgroundColor: "#1a1310",
  gridColor: "rgba(120,90,60,0.15)",
  hasDarkness: false,
  hasFlashlight: false,
  hasGenerator: false,
  stations: [
    { wx: "smg", x: 500, y: 500, label: "SMG" },
    { wx: "shotgun", x: 1900, y: 500, label: "Shotgun" },
    { wx: "rifle", x: 500, y: 1400, label: "Rifle" },
    { wx: "plasma", x: 1900, y: 1400, label: "Plasma" },
  ],
  worldObjects: [
    { pos: { x: 400, y: 400 }, color: "#ff0000", radius: 15, questId: "sq_lights", stepId: "l1" },
    { pos: { x: 2000, y: 400 }, color: "#00ff00", radius: 15, questId: "sq_lights", stepId: "l2" },
    { pos: { x: 1200, y: 1400 }, color: "#0000ff", radius: 15, questId: "sq_lights", stepId: "l3" },
  ],
  mainQuest: [
    {
      id: "m1",
      text: "Hold the Outpost Radio (NW) for 10s",
      type: "reach",
      location: { x: 300, y: 300 },
      done: false,
    },
    {
      id: "m2",
      text: "Purge the horde: kill 15 zombies",
      type: "kill",
      target: 15,
      progress: 0,
      done: false,
    },
    { id: "m3", text: "Buy a new weapon at any station", type: "buy", done: false },
    {
      id: "m4",
      text: "Slay 7 zombies near the Sector Key (SE ruin)",
      type: "kill",
      target: 7,
      progress: 0,
      location: { x: 2050, y: 1500 },
      done: false,
    },
    {
      id: "m5",
      text: "Enter the Underworld Gate (center)",
      type: "reach",
      location: { x: 1200, y: 900 },
      done: false,
    },
  ],
  sideQuests: [
    {
      id: "sq_lights",
      title: "The RGB Sequence",
      accepted: true,
      done: false,
      reward: "MAX_RESOURCES",
      steps: [
        {
          id: "l1",
          text: "Shoot the Red Light",
          type: "shoot",
          color: "#ff0000",
          location: { x: 400, y: 400 },
          done: false,
        },
        {
          id: "l2",
          text: "Shoot the Green Light",
          type: "shoot",
          color: "#00ff00",
          location: { x: 2000, y: 400 },
          done: false,
        },
        {
          id: "l3",
          text: "Shoot the Blue Light",
          type: "shoot",
          color: "#0000ff",
          location: { x: 1200, y: 1400 },
          done: false,
        },
      ],
    },
    {
      id: "sq_supply",
      title: "Supply Run: Recover 4 Crates",
      accepted: true,
      done: false,
      reward: 300,
      steps: [
        {
          id: "c1",
          text: "Recover crate — NW ruins",
          type: "reach",
          location: { x: 300, y: 900 },
          done: false,
        },
        {
          id: "c2",
          text: "Recover crate — NE outpost",
          type: "reach",
          location: { x: 2100, y: 900 },
          done: false,
        },
        {
          id: "c3",
          text: "Recover crate — south depot",
          type: "reach",
          location: { x: 800, y: 1500 },
          done: false,
        },
        {
          id: "c4",
          text: "Recover crate — east alley",
          type: "reach",
          location: { x: 1700, y: 1500 },
          done: false,
        },
      ],
    },
  ],
  gatePos: { x: 1200, y: 900 },
  bossType: "harvester",
  bossHp: 1500,
  bossRadius: 46,
  easterEggType: "rgb",
};
